language: node_js
cache: yarn
node_js:
  -  "9"
install: yarn
script: yarn build
deploy:
  provider: s3
  access_key_id: "AKIAIO6AIGXDGOFBCGPA"
  secret_access_key: "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"
  bucket: "les3"
  local_dir: public
