language: node_js
cache: yarn
node_js:
  -  "9"
install: yarn
script: yarn build
deploy:
  provider: s3
  access_key_id: "AKIAJMVQL334V3YJ5P5Q"
  secret_access_key: "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"
  bucket: "les3"
  local_dir: build
  skip_cleanup: true
